### ISSUE TITLE
[Bug] unable to find llvm-bindings.node

### ISSUE THREAD

**Issue by rishavs** [ApsarasX/llvm-bindings#35]
**Your environment**
- OS version:  Linux 5.10.102.1-microsoft-standard-WSL2 x86_64 GNU/Linux
- Node.js version: 12.22.9
- LLVM version: 14.0.6

**Describe the bug**
when I try to run my ts project using esbuild, i get the error that it is unable to find the llvm-bindings.node file.

```
rishav@Rishav-SB3:~/tyll$ npm run dev

> tyll@1.0.0 dev
> esbuild --bundle tyll.ts --format=esm --log-level=warning --platform=node --outfile=dist/compiled.js && node dist/compiled.js

/home/rishav/tyll/dist/compiled.js:145
      throw err;
      ^

Error: Could not locate the bindings file. Tried:
 → /home/rishav/tyll/build/llvm-bindings.node
 → /home/rishav/tyll/build/Debug/llvm-bindings.node
 → /home/rishav/tyll/build/Release/llvm-bindings.node
 → /home/rishav/tyll/out/Debug/llvm-bindings.node
 → /home/rishav/tyll/Debug/llvm-bindings.node
 → /home/rishav/tyll/out/Release/llvm-bindings.node
 → /home/rishav/tyll/Release/llvm-bindings.node
 → /home/rishav/tyll/build/default/llvm-bindings.node
 → /home/rishav/tyll/compiled/12.22.9/linux/x64/llvm-bindings.node
 → /home/rishav/tyll/addon-build/release/install-root/llvm-bindings.node
 → /home/rishav/tyll/addon-build/debug/install-root/llvm-bindings.node
 → /home/rishav/tyll/addon-build/default/install-root/llvm-bindings.node
 → /home/rishav/tyll/lib/binding/node-v72-linux-x64/llvm-bindings.node
    at bindings (/home/rishav/tyll/dist/compiled.js:139:13)
    at node_modules/llvm-bindings/index.js (/home/rishav/tyll/dist/compiled.js:199:40)
    at __require2 (/home/rishav/tyll/dist/compiled.js:15:50)
    at Object.<anonymous> (/home/rishav/tyll/dist/compiled.js:204:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  tries: [
    '/home/rishav/tyll/build/llvm-bindings.node',
    '/home/rishav/tyll/build/Debug/llvm-bindings.node',
    '/home/rishav/tyll/build/Release/llvm-bindings.node',
    '/home/rishav/tyll/out/Debug/llvm-bindings.node',
    '/home/rishav/tyll/Debug/llvm-bindings.node',
    '/home/rishav/tyll/out/Release/llvm-bindings.node',
    '/home/rishav/tyll/Release/llvm-bindings.node',
    '/home/rishav/tyll/build/default/llvm-bindings.node',
    '/home/rishav/tyll/compiled/12.22.9/linux/x64/llvm-bindings.node',
    '/home/rishav/tyll/addon-build/release/install-root/llvm-bindings.node',
    '/home/rishav/tyll/addon-build/debug/install-root/llvm-bindings.node',
    '/home/rishav/tyll/addon-build/default/install-root/llvm-bindings.node',
    '/home/rishav/tyll/lib/binding/node-v72-linux-x64/llvm-bindings.node'
  ]
}
```
**Expected behavior**

I would expect that the llvm-bindings.node file would be correctly fetched from its location in the npm modules.

To unblock myself, I have currently copied the file into ./Release/llvm-bindings.node path

**Comment by grngxd** [comment]
any update on this?
